# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      setupCall: ''
    mac:
      imageName: 'macos-10.13'
      setupCall: 'xcode-select --switch /Applications/Xcode_10.1.app'
    windows:
      imageName: 'vs2017-win2016'
      setupCall: ''

pool:
  vmImage: $(imageName)



steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: $(setupCall)
  displayName: 'Setup environment'

- script: 'git submodule update --init --recursive'
  displayName: 'Checkout submodules'
  
- script: 'python build.py'
  displayName: 'Build vcpkg ports'
