# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Build
  timeoutInMinutes: 360

  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
        CXX: '/usr/bin/clang++'
        CC: '/usr/bin/clang'
        buildPlatform: 'linux'
        fs: '/'
      mac:
        imageName: 'macos-10.13'
        DEVELOPER_DIR: '/Applications/Xcode_10.1.app'
        VCPKG_ALLOW_APPLE_CLANG: true
        buildPlatform: 'osx'
        fs: '/'
      windows:
        imageName: 'vs2017-win2016'
        buildPlatform: 'windows'
        fs: '\\'

  variables:
    VCPKG_ROOT: '$(Build.SourcesDirectory)/vcpkg'
    archiveFile: $(Build.ArtifactStagingDirectory)$(fs)flimfit-env-$(buildPlatform).7z

  pool:
    vmImage: $(imageName)

  steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
      
    - script: 'brew install gcc p7zip'
      displayName: 'Install brew dependencies'
      condition: eq(variables['buildPlatform'],'osx')


    - script: 'python build.py'
      displayName: 'Build vcpkg ports'

    - task: CopyFiles@2
      condition: always() 
      inputs:
        contents: |
          'vcpkg$(fs)buildtrees$(fs)*$(fs)*.log'
          'vcpkg$(fs)buildtrees$(fs)*$(fs)*$(fs)CMakeFiles$(fs)*.log'
        targetFolder: logs
      
    - task: PublishBuildArtifacts@1
      condition: always() 
      inputs:
        pathtoPublish: logs
        artifactName: vcpkg-logs-$(buildPlatform)
      
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'vcpkg'
        archiveType: '7z'
        archiveFile: $(archiveFile)

    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: $(archiveFile)
        artifactName: 'flimfit-env-$(buildPlatform).7z'

    - task: GithubRelease@0
      displayName: 'Create GitHub Release'
      inputs:
        githubConnection: seanwarren
        repositoryName: seanwarren/flimfit-env
        assets: $(archiveFile)